server:
  # 端口
  port: 6001
  servlet:
    # 项目名称
    context-path : /juntech

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/juntech_dev?characterEncoding=UTF-8&useUnicode=true&useSSL=false&verifyServerCertificate=false&requireSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: juntech
    password: juntech123
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型

mybatis-plus:
  #匹配sql语句的映射文件的位置
  mapper-locations: classpath*:org/juntech/**/mapper/xml/*.xml
  #以下两个配置可以省略，然后在mapper映射文件中配置也是可以的。
  #使用type-aliases-package中指定entity扫描包类让mybatis自定扫描到自定义的entity
  type-aliases-package: org.juntech
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true

#
#spring:
#  datasource:
#    druid:
#      stat-view-servlet:
#        enabled: true
#        loginUsername: admin
#        loginPassword: qd!23#
#        allow:
#      web-stat-filter:
#        enabled: true
#    dynamic:
#      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
#        # 连接池的配置信息
#        # 初始化大小，最小，最大
#        initial-size: 5
#        min-idle: 5
#        maxActive: 20
#        # 配置获取连接等待超时的时间
#        maxWait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        timeBetweenEvictionRunsMillis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        # 打开PSCache，并且指定每个连接上PSCache的大小
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(不支持达梦，此处去掉,wall)
#        filters: stat,slf4j
#        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      datasource:
#        master:
#          # MySQL数据库连接
#          url: jdbc:mysql://127.0.0.1:13306/juntech_dev?characterEncoding=UTF-8&useUnicode=true&useSSL=false&verifyServerCertificate=false&requireSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#          username: juntech
#          password: juntech123
#          driver-class-name: com.mysql.cj.jdbc.Driver